"""add title to book_details

Revision ID: 0cea55398f72
Revises: 14dec3d5ea6a
Create Date: 2024-07-19 02:20:32.114973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cea55398f72'
down_revision = '14dec3d5ea6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=False))

    with op.batch_alter_table('borrowed_books', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('return_date',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrowed_books', schema=None) as batch_op:
        batch_op.alter_column('return_date',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('book_details', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
