"""Add name column to comments table

Revision ID: abdbf49c9aba
Revises: f4b46bd7bc7d
Create Date: 2024-07-17 09:02:37.671305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abdbf49c9aba'
down_revision = 'f4b46bd7bc7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
