"""Add description and ISBN to Book model

Revision ID: c706725f8ad8
Revises: 9cb5e69b6f16
Create Date: 2024-07-17 09:34:11.893596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c706725f8ad8'
down_revision = '9cb5e69b6f16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('isbn', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('isbn')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
